services:
  - type: web
    name: cassita
    runtime: node  # Указываем среду выполнения
    build:
      command: npm install && npm run build
    start: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    region: frankfurt